// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: books.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (id, isbn, name, author, publication, created_at, updated_at)
VALUES (
    $1,$2,$3,$4,$5,$6,$7
)
RETURNING id, isbn, name, author, publication, created_at, updated_at
`

type CreateBookParams struct {
	ID          uuid.UUID
	Isbn        string
	Name        string
	Author      string
	Publication string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.ID,
		arg.Isbn,
		arg.Name,
		arg.Author,
		arg.Publication,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Name,
		&i.Author,
		&i.Publication,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, isbn, name, author, publication, created_at, updated_at FROM books
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Name,
		&i.Author,
		&i.Publication,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, isbn, name, author, publication, created_at, updated_at FROM books
ORDER BY name
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Name,
			&i.Author,
			&i.Publication,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookName = `-- name: UpdateBookName :exec
UPDATE books
SET name = $3, updated_at = $2
WHERE id = $1
`

type UpdateBookNameParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) UpdateBookName(ctx context.Context, arg UpdateBookNameParams) error {
	_, err := q.db.ExecContext(ctx, updateBookName, arg.ID, arg.UpdatedAt, arg.Name)
	return err
}
