// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID          uuid.UUID
	Isbn        string
	Name        string
	Author      string
	Publication string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
