services:
  app:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image:  postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Na03password
      POSTGRES_DB: booker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
